### ISSUE TITLE
When create a database get many sql errors

### ISSUE THREAD

**Issue by css-ilgol** [zvic81/flask_api#1]
You need to improve simplification of setting up db environment.

```
psql -hlocalhost -Upostgres -W -dflask_db -fflask_db.sql 
Password: 
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
SET
SET
CREATE TABLE
ALTER TABLE
ALTER TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
 setval 
--------
     11
(1 row)

ALTER TABLE
psql:flask_db.sql:83: ERROR:  role "flask_user" does not exist
psql:flask_db.sql:84: ERROR:  role "pg_read_all_data" does not exist
psql:flask_db.sql:85: ERROR:  role "pg_write_all_data" does not exist
psql:flask_db.sql:86: ERROR:  role "pg_database_owner" does not exist
psql:flask_db.sql:93: ERROR:  role "flask_user" does not exist

```

**Comment by zvic81** [comment]
я не знаю почему. на своей машине проверял.предлагаю посмотреть создалась ли база flask_db, ест ли данные в ней, создать роль flask_user руками, дать права на базу

  
>Пятница, 30 сентября 2022, 14:57 +03:00 от css-ilgol ***@***.***>:
> 
> 
>You need to improve simplification of setting up db environment.
>psql -hlocalhost -Upostgres -W -dflask_db -fflask_db.sql 
>Password: 
>SET
>SET
>SET
>SET
>SET
> set_config 
>------------
> 
>(1 row)
>
>SET
>SET
>SET
>SET
>SET
>SET
>CREATE TABLE
>ALTER TABLE
>ALTER TABLE
>INSERT 0 1
>INSERT 0 1
>INSERT 0 1
>INSERT 0 1
>INSERT 0 1
>INSERT 0 1
> setval 
>--------
>     11
>(1 row)
>
>ALTER TABLE
>psql:flask_db.sql:83: ERROR:  role "flask_user" does not exist
>psql:flask_db.sql:84: ERROR:  role "pg_read_all_data" does not exist
>psql:flask_db.sql:85: ERROR:  role "pg_write_all_data" does not exist
>psql:flask_db.sql:86: ERROR:  role "pg_database_owner" does not exist
>psql:flask_db.sql:93: ERROR:  role "flask_user" does not exist
>
>
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <zvic81/flask_api/issues/1 @ github . com> 
 
 
С уважением,

***@***.***
